trigger:
  - main
  - dev

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'npm install'

  - script: |
      npm run lint
    displayName: 'npm run lint'

  - script: |
      npm run build
    displayName: 'npm run build'

  - task: Docker@2
    displayName: Build and push an image to container registry
    inputs:
      containerRegistry: 'openapi-test-docker-sc'
      repository: 'openapi/sdk-generation'
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile'
      tags: '$(Build.BuildNumber)'

  - task: DockerCompose@0
    displayName: "docker-compose up"
    inputs:
      dockerComposeFile: "**/docker-compose.yml"
      dockerComposeFileArgs: "NODE_ENV=development"
      qualifyImageNames: false
      action: "run A Docker Compose Command"
      dockerComposeCommand: "up --build --detach --remove-orphans --force-recreate --renew-anon-volumes"
      buildImages: true
      detached: true

  - script: |
      npm run test
    displayName: 'npm run test'

